// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADJr3f_2zy9GAOkDRUngS2njNLup7H28k',
    appId: '1:192874940036:web:9fac73f4a6a578e9de24d1',
    messagingSenderId: '192874940036',
    projectId: 'flutter-firebase-login-storage',
    authDomain: 'flutter-firebase-login-storage.firebaseapp.com',
    storageBucket: 'flutter-firebase-login-storage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxrAlHlm_ROSORcLQYY3KPS5jV1SOlTgQ',
    appId: '1:192874940036:android:175589836b473fe6de24d1',
    messagingSenderId: '192874940036',
    projectId: 'flutter-firebase-login-storage',
    storageBucket: 'flutter-firebase-login-storage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl339MyMXvEH86bUPVsAJC01GidqOQpeM',
    appId: '1:192874940036:ios:1a937dd3742698d6de24d1',
    messagingSenderId: '192874940036',
    projectId: 'flutter-firebase-login-storage',
    storageBucket: 'flutter-firebase-login-storage.firebasestorage.app',
    iosBundleId: 'com.Karthik.yelloskyeTest',
  );

}